### ISSUE TITLE
How to get audio with beamforming ?

### ISSUE THREAD

**Issue by EvanFang1013** [STMicroelectronics/BlueSTSDK_Python#10]
I can get audio with beamforming on the direction  from ios/android,
but i don't know how to get that function on python.
I have found beamforming of feature on python ,but that only return direction.
I want to get audio data with beamforming, can you teach me how to do ?
please help ,thank you.

**Comment by matteoronchi** [comment]
Hi EvanFang1013,

I've just updated the "example_ble_5.py" adding the possibility to activate the beamforming (if it is a feature exported from the BLE node you are using).
I hope that this could solve your issue.

best regards,
Matteo

**Comment by EvanFang1013** [comment]
Dear matteoronchi ,
Thanks your solution,
I successfully activate the  beamforming
Best regards.
