### ISSUE TITLE
cannot detect the sensor using the program(example_ble_1.py)

### ISSUE THREAD

**Issue by ArthurKun21** [STMicroelectronics/BlueSTSDK_Python#14]
Python 3.7.3
Bluetooth 5.0
Raspberry Pi 4B
Raspbian Buster September 2019 Version

The Program(example_ble_1.py and example_ble_2.py) cannot detect the sensor (PM1V200) but if using the native bluetooth it manages to detect the sensor(PM1V200)

![2019-10-08-095126_1024x768_scrot](https://user-images.githubusercontent.com/16458204/66361422-49e8fd80-e9b1-11e9-81b5-b42b1bb02b7b.png)

edit: added Raspberry Pi software Version

**Comment by davidroid** [comment]
Dear Rulerkun,
as you can read in the "Setting up the application examples" section of the
repository page, the SDK is compatible only with devices equipped with a
firmware that embeds the BlueST Protocol.

Regards,
Davide

Il giorno mar 8 ott 2019 alle ore 03:55 Rulerkun <notifications@github.com>
ha scritto:

**Comment by ArthurKun21** [comment]
yes, we are using devices equipped with a firmware that embeds the BlueST Protocol.

https://www.st.com/resource/en/product_presentation/fp-ind-predmnt1_quick_start_guide.pdf

 STM32 Nucleo with expansion boards
• NUCLEO-F446RE + X-NUCLEO-CCA02M1 + X-NUCLEO-IDB05A1 + X-NUCLEO-IKS01A2 + STEVAL-MKI182V2

![image](https://user-images.githubusercontent.com/16458204/66363117-b1a24700-e9b7-11e9-9e33-eb18851a6991.png)

**Comment by ArthurKun21** [comment]
edit the first comment
- added Raspbian version

**Comment by davidroid** [comment]
Ok, now I understand. The FP-IND-PREDMNT1 is not supported yet; you can find the supported features in the "Note" section of the "BlueST Protocol" chapter of the readme file.

We are continuously adding features, and the predictive maintenance is on the roadmap, so please check here for updates.

Thank you for your interest and regards,
Davide

**Comment by ArthurKun21** [comment]
yes although i understand that the preventive maintenance is not yet implemented. We just need to get some basic data like temperature, pressure and humidity for testing purposes. How can we do that? the program can't detect the sensor?

**Comment by ArthurKun21** [comment]
my colleague managed to make it work out with the RPi3, the part where getting the temperature,pressure and humidity but not on the RPi4. Could i know what some parts we need to check so we could fix and make it work in the RPi 4?

**Comment by davidroid** [comment]
Don't have at the moment a PI4 to try, but I will manage to try it. There
shouldn't be any difference, anyway.
Are you maybe missing some library?

Regards,
Davide


Il giorno mer 9 ott 2019 alle ore 02:53 Rulerkun <notifications@github.com>
ha scritto:

**Comment by ArthurKun21** [comment]
Hi @davidroid 

I found the problem here, the python 3.7.3 have a problem with the bluepy library. The solution is to downgrade it to python 3.5.7 and now it works.

> Are you maybe missing some library?  

No Sir, i have installed all of the libraries here
- sudo apt-get install python3-pip libglib2.0-dev
- sudo pip3 install bluepy
- sudo pip3 install futures
- sudo pip3 install blue-st-sdk
- pip install enum34



We are now just waiting for the predictive maintenance feature of BlueSTSDK Python. Can we have the estimated time of release of this feature?

**Comment by davidroid** [comment]
Ok, good to know.

I hope to have time to work on it soon in this quarter.

Thank you and regards,
Davide


Il gio 10 ott 2019, 03:27 Rulerkun <notifications@github.com> ha scritto:
