### ISSUE TITLE
How to configure the Program to be able to let it connect to multiple devices

### ISSUE THREAD

**Issue by reokyouma** [STMicroelectronics/BlueSTSDK_Python#16]
When my Raspberry Pi with [BLUEST-SDK-PYTHON](https://github.com/STMicroelectronics/BlueSTSDK_Python) is connecting to the STWINKT, my Android Phone with [ST BLE Sensor app](https://play.google.com/store/apps/details?id=com.st.bluems&hl=en) cannot connect to it and When my Android Phone is connect to STWINKT, my Raspberry PI cannot discover or connect into it [(I am using exampe_ble_1.py)](https://github.com/STMicroelectronics/BlueSTSDK_Python/blob/master/blue_st_examples/example_ble_1.py)

How to configure the Program to be able to let it connect to multiple devices

**Comment by davidroid** [comment]
Hello reokyouma,
what you are looking for is a kind of mesh network, and this is not feasible with the firmware of the STWIN kit, i.e. whenever a node is connected to a mobile/gateway, it cannot be discovered again by another device.
If you are interested on the topic I suggest you to have a look to mesh networks, but in any case you will need to modify the firmware.

Regards,
Davide
