### ISSUE TITLE
How to get sensor fusion results

### ISSUE THREAD

**Issue by PeterBee97** [STMicroelectronics/BlueSTSDK_Python#6]
For update of issue #2 , current version of Python SDK offers activity recognition results output. Is there any way to get the sensor fusion feature output as you can on Android? Is this an scheduled update to the Python SDK or is it already possible to do it with the current version with some function I fail to see? Thanks for helping.

**Comment by davidroid** [comment]
Hello Peter,
Not yet, but it's in the pipeline. Hopefully the missing features w.r.t.
Android will be integrated in this quarter.

Best regards,
Davide


Il lun 1 apr 2019, 22:50 Peter Bee <notifications@github.com> ha scritto:

**Comment by PeterBee97** [comment]
Thanks David. Looking forward to it :)

**Comment by Harsharma2308** [comment]
Wanted to follow up whether this is being released soon.
